# Generated by Django 4.2 on 2023-04-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabSweetUser', '0002_attribute_rename_samplebatch_sample_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='abbreviated_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='completed',
            field=models.DateTimeField(),
        ),
    ]
