# Generated by Django 4.2 on 2023-04-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabSweetUser', '0003_alter_attribute_abbreviated_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='abbreviated_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
