# Generated by Django 4.2 on 2023-04-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabSweetUser', '0004_alter_attribute_abbreviated_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='attribute',
        ),
        migrations.AlterField(
            model_name='test',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='result',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
