# Generated by Django 4.2 on 2023-04-26 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabSweetUser', '0005_rename_name_test_attribute_alter_test_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('due', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='sample',
            name='complete',
        ),
        migrations.AddField(
            model_name='test',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='LabSweetUser.job'),
        ),
    ]
