# Generated by Django 4.2 on 2023-04-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabSweetUser', '0006_job_remove_sample_complete_test_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='uploaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
