# Generated by Django 4.2 on 2023-04-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabSweetUser', '0007_test_uploaded_alter_sample_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='uploaded',
            new_name='date_completed',
        ),
    ]
