# Generated by Django 4.2 on 2023-04-30 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabSweetUser', '0008_rename_uploaded_test_date_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='job',
        ),
        migrations.AddField(
            model_name='sample',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='LabSweetUser.job'),
        ),
    ]
