# Generated by Django 4.2 on 2023-05-01 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabSweetUser', '0009_remove_test_job_sample_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='LabSweetUser.job'),
        ),
    ]
