# Generated by Django 4.2 on 2023-05-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabSweetUser', '0010_alter_sample_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='completed',
            new_name='complete',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='updated',
        ),
        migrations.AddField(
            model_name='sample',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
