# Generated by Django 4.2 on 2023-05-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabSweetUser', '0011_rename_completed_test_complete_remove_sample_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='abbreviated_name',
        ),
        migrations.AddField(
            model_name='attribute',
            name='full_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
