# Generated by Django 4.2 on 2023-07-23 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabSweetUser', '0013_rename_due_job_due_date_rename_number_job_job_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='test',
            name='date_completed',
        ),
    ]
