# Generated by Django 4.2 on 2023-07-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabSweetUser', '0014_remove_test_complete_remove_test_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
