# Generated by Django 4.2 on 2023-08-01 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabSweetUser', '0015_test_date_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worklist_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='worklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='LabSweetUser.worklist'),
        ),
    ]
