# Generated by Django 4.2 on 2023-08-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabSweetUser', '0016_worklist_test_worklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklist',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='worklists'),
        ),
    ]
