# Generated by Django 4.2 on 2023-08-26 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabSweetUser', '0017_worklist_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='due_date',
        ),
    ]
