# Generated by Django 4.2 on 2025-02-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabSweetUser', '0019_auto_20230916_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(choices=[('AFB', 'American Foulbrood'), ('DIA', 'Diastase'), ('GLY', 'Glyphosate'), ('UMF', 'UMF'), ('TUT', 'Tutin')], max_length=3),
        ),
    ]
